package com.hospital.enums;

public enum HospitalEventType {
    PATIENT_REGISTERED,
    EMERGENCY_CREATED,
    DOCTOR_ASSIGNED,
    BED_ASSIGNED,
    BED_RELEASED,
    LAB_COMPLETED,
    PRESCRIPTION_CREATED,
    MEDICINE_SOLD,
    PAYMENT_COMPLETED,
    OPERATION_STARTED,
    OPERATION_COMPLETED,
    AMBULANCE_ASSIGNED,
    BLOOD_ISSUED,
    PATIENT_DISCHARGED,
    FOLLOW_UP_CREATED
}
